{% set name = "yagmail" %}
{% set version = "0.15.293" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44e8d0cda4f63e22a14902cc9096d52197fd0ced023d50b0409325f401585296

build:
  number: 1
  noarch: python
  entry_points:
    - yagmail = yagmail.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - premailer
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - yagmail
  commands:
    - yagmail --help

about:
  home: https://github.com/kootenpv/yagmail
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yet Another GMAIL client

extra:
  recipe-maintainers:
    - setu4993
