{% set name = "yagmail" %}
{% set version = "0.12.233" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c103b9b9126dac90dca07a3a4b9dc7a3a5cda8f588096c8b2187a0b6a2dfae2d

build:
  number: 0
  noarch: python
  entry_points:
    - yagmail = yagmail.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - yagmail
  commands:
    - yagmail --help

about:
  home: https://github.com/kootenpv/yagmail
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yet Another GMAIL client

extra:
  recipe-maintainers:
    - setu4993
